name: Fetch JSON Every 1 Minute

on:
  schedule:
    - cron: '*/1 * * * *'  # Alle 1 Minute
  workflow_dispatch:  # Ermöglicht manuelles Starten

jobs:
  fetch_json:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Run PHP Script
        run: php fetch_json.php

      - name: Commit and Push Changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add output.json
          git commit -m "Updated JSON data"
          git push
