name: Fetch JSON and Commit

on:
  schedule:
    - cron: '*/10 * * * *'  # Alle 10 Minuten

jobs:
  fetch-json:
    runs-on: ubuntu-latest
    steps:
      # Repository auschecken
      - name: Checkout repository
        uses: actions/checkout@v2

      # PHP-Setup (wenn du Composer oder PHP installieren musst)
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'  # oder deine PHP-Version

      # PHP-Skript ausführen
      - name: Run PHP Script
        run: |
          php fetch_json.php  # Dein PHP-Skript, das die JSON-Daten abruft und speichert

      # Git-Setup (falls noch nicht konfiguriert)
      - name: Set up git user
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      # Commit und Push der Änderungen
      - name: Commit and push changes
        run: |
          git add output.json
          git commit -m "Updated JSON data with timestamp" || exit 0
          git push origin main  # oder master, je nach deinem Branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Token für Push
